version: '3'
services:
  certbot:
    restart: always
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ~/certbot/www:/var/www/certbot/:rw
      - ~/certbot/conf:/etc/letsencrypt/:rw
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./templates:/etc/nginx/templates
      - ~/certbot/www:/var/www/certbot/:ro
      - ~/certbot/conf:/etc/nginx/ssl/:ro
  frontend:
    restart: always
    image: victorycenterua/client:release-${DOCKER_TAG_FRONTEND}
    pull_policy: always
    container_name: frontend
    expose:
      - "80"
    environment:
      REACT_APP_BACKEND_URL: "https://backend.historycode.online/api"
  backend:
    restart: always
    image: victorycenterua/backend:release-${DOCKER_TAG_BACKEND}
    container_name: backend
    pull_policy: always
    expose:
      - "80:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      INITIAL_ADMIN_EMAIL: ${INITIAL_ADMIN_EMAIL}
      INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD}
      JWTOPTIONS_SECRETKEY: ${JWTOPTIONS_SECRETKEY}
      JWTOPTIONS_REFRESH_TOKEN_SECRETKEY: ${JWTOPTIONS_REFRESH_TOKEN_SECRETKEY}
volumes:
  backend:
networks:
  backend:
    external: true
    name: backend
  frontend:
    external: true
    name: frontend
