---
- name: Install Github Action Runner on VM
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    hide_sensitive_logs: true
    runner_user: "{{ runner_user }}"
    runner_dir: "/home/{{ runner_user }}/actions-runner"
    github_account: "{{ github_account }}"
    github_repo: "{{ github_repo }}"
    runner_version: "latest"
    runner_config_labels: "Stage, self-hosted-vm"
    access_token: "{{ secrets.PERSONAL_ACCESS_TOKEN }}"
  roles:
    - role: monolithprojects.github_actions_runner
